### ISSUE TITLE
Replace GLPK with ojAlgo

### ISSUE THREAD

**Issue by pietrobraione** [pietrobraione/sushi#6]
Ideally SUSHI should be a pure Java application. Currently the only native part is GLPK, and apparently the only pure Java replacement that is actively developed is ojAlgo (http://ojalgo.org/). Evaluate whether it is the case to replace GLPK with ojAlgo.

**Comment by apete** [comment]
Is it an LP or a MIP? How large? I have no experience with GLPK, but ojAlgo is far from as fast as CPLEX, GUROBI or MOSEK for larger/harder problems.

One good thing with ojAlgo is that you can plug in and use other solvers. The are already integrations for CPLEX, GUROBI and MOSEK. Writing one for GLPK should be easy. This way you can switch between using different solvers without changing any code.

**Comment by pietrobraione** [comment]
It is a MIP with binary variables, an instance of a minimal coverage problem. Its description is [here](https://github.com/pietrobraione/sushi/blob/729a73e1d3c88ef4cfc79ffba4913297ddd07243/master/src/main/java/sushi/execution/minimizer/RunMinimizer.java#L201). I would not give data about how large the problem should be, because it all depends on the software SUSHI is generating tests for, and of course the larger the better. Right now I would be happy with an order of magnitude of tens from hundred of thousand of variables and hundred to thousand of linear constraint. Consider that solving the MIP is not the slowest part of the procedure: symbolic execution and genetic test generation are waaaay slower and dominate completely the execution time of SUSHI.  The fact that ojAlgo can also be used as an interface to other solvers is definitely a plus.

**Comment by apete** [comment]
Give it a try! I don't think it will be hard to rewrite that code using ojAlgo's ExpressionsBasedModel. You get the basics from this simple example:

https://github.com/optimatika/ojAlgo/wiki/The-Diet-Problem

Integrating solvers is not hard either. Here are 3 example integrations:

- https://github.com/optimatika/ojAlgo-extensions/blob/develop/ojAlgo-cplex/src/main/java/org/ojalgo/optimisation/solver/cplex/SolverCPLEX.java
- https://github.com/optimatika/ojAlgo-extensions/blob/develop/ojAlgo-gurobi/src/main/java/org/ojalgo/optimisation/solver/gurobi/SolverGurobi.java
- https://github.com/optimatika/ojAlgo-extensions/blob/develop/ojAlgo-mosek/src/main/java/org/ojalgo/optimisation/solver/mosek/SolverMosek.java

**Comment by pietrobraione** [comment]
Integrated ojAlgo with commit ebe9b5a.
